kind: pipeline
type: kubernetes
name: default

platform:
    os: linux
    arch: arm64

steps:
    # - name: frontend
    #   image: node
    #   volumes:
    #       - name: cache
    #         path: /whl-fe
    #   commands:
    #       - yarn --cwd web --network-timeout 100000
    #       - yarn --cwd web build
    - name: backend
      image: node
      commands:
          - npm i --prefix server
          - npm test --prefix server
          - npm run build --prefix server
