kind: pipeline
type: kubernetes
name: default

platform:
    os: linux
    arch: arm64

steps:
    # - name: frontend
    #   image: node
    #   volumes:
    #       - name: cache
    #         path: /whl-fe
    #   commands:
    #       - yarn --cwd web --network-timeout 100000
    #       - yarn --cwd web build
    - name: backend
      image: node
      volumes:
          - name: cache
            path: /drone/src/server/node_modules
      commands:
          - ls server
          - npm i --prefix server
          - npm run build --prefix server
          - npm test --prefix server
      environment:
          TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432?sslmode=disable"
          TEST_REDIS_URL: redis://127.0.0.1

volumes:
    - name: cache
      host:
          path: /var/lib/cache

services:
    - name: cache
      image: redis
    - name: database
      image: postgres
      environment:
          POSTGRES_PASSWORD: postgres
