kind: pipeline
type: kubernetes
name: default

platform:
    os: linux
    arch: arm64z

steps:
    - name: test
      image: docker:dind
      volumes:
          - name: dockersock
            path: /var/run/
      commands:
          - docker info
          - docker buildx build --platform linux/amd64 -t dokku/webhooklogsapi .

volumes:
    - name: dockersock
      host:
          path: /var/run/
