kind: pipeline
type: kubernetes
name: default

platform:
    os: linux
    arch: arm64

steps:
    - name: test
      image: docker:dind
      volumes:
          - name: dockersock
            path: /var/run/
      commands:
          - docker ps -a

volumes:
    - name: dockersock
      host:
          path: /var/run/
