apiVersion: apps/v1
kind: Deployment
metadata:
    name: graphql-api
    namespace: hookhub-stage
    labels:
        app: graphql-api
spec:
    replicas: 3
    selector:
        matchLabels:
            app: graphql-api
    template:
        metadata:
            labels:
                app: graphql-api
        spec:
            restartPolicy: Always
            containers:
                - name: graphql-api
                  image: florianherrengt/docker-tutorial
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3001
                  env:
                      - name: PORT
                        value: "3000"
---
apiVersion: v1
kind: Service
metadata:
    name: graphql-api
    namespace: hookhub-stage
    labels:
        app: graphql-api
spec:
    ports:
        - port: 3001
          targetPort: 3001
          protocol: TCP
    selector:
        app: graphql-api
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: graphql-api
    namespace: hookhub-stage
    annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/issuer: "letsencrypt"
spec:
    tls:
        - hosts:
              - topfloorflat.com
          secretName: graphql-api-tls
    rules:
        - host: topfloorflat.com
          http:
              paths:
                  - backend:
                        serviceName: graphql-api
                        servicePort: 3001
                    path: /
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
    name: letsencrypt
    namespace: hookhub-stage
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: contact@topfloorflat.com
        privateKeySecretRef:
            name: letsencrypt
        solvers:
            - http01:
                  ingress:
                      class: nginx
